### ISSUE TITLE
[Question/hw1] Question about Definition of 'Sorted' and 'Partitioned' in formula.ml

### ISSUE THREAD

**Issue by tori209** [gist-pal/ec4219-software-engineering#1]
### Kor version.

Lec12의 p.6의 "pre(F, x[e1] := e2) ⇔ F[x 〈 e1 ◁  e2 〉 / x]"을 보니, Array 수정에 대한 precondition 처리는 command를 이용하여 갱신된 새로운 Array로 Substitute하는 것과 동일한 동작을 수행합니다.
위의 관계를 참고한다면 "pre( sorted(a, t1, t2) , a[e1] := e2 ) ⇔ sorted ( a 〈 e1 ◁  e2 〉, t1, t2 )" 또한 옳은 관계라고 생각합니다.

'formula.ml' 파일에서 "a 〈 e1 ◁  e2 〉" 과 동일한 의미를 갖는 요소는 "Write (a, t1, t2)", 즉 term의 한 종류라고 생각됩니다.
하지만 동일 파일의 Sorted와 Partitioned의 경우 array가 위치하는 곳(tuple의 첫번째 element)의 타입을 var로 지정하고 있어, Write를 대입하는 substitution이 불가능한 것 같습니다.

위의 경우들에 대해 Substitution을 수행하지 않아도 정상적으로 동작하는 것인지, 아니면 var 대신 term으로 정의를 바꾸어야 하는 것인지 궁금합니다.

---

### Eng. version

According to relation "pre(F, x[e1] := e2) ⇔ F[x 〈 e1 ◁  e2 〉 / x]" in Lec 12, p.6, precondition of assignment on array is equivalent to substitution of original array using modified array.
From this, I think that this relation is also correct: "pre( sorted(a, t1, t2) , a[e1] := e2 ) ⇔ sorted ( a 〈 e1 ◁  e2 〉, t1, t2 )"

Maybe, in 'formula.ml' file, meaning of "a 〈 e1 ◁  e2 〉" is equivalent to "Write (a, t1, t2)", which is a kind of Formula.term. 
But, since the type of first element of 'Sorted' and 'Partitioned' is 'var', substitution from a to a 〈 e1 ◁  e2 〉 seems to not be implemented. 

So, my question is, Should we change the definition of Sorted and Partitioned? or Can our verifier work well even without substitution on those cases?

**Comment by sunbeomso** [comment]
@tori209 

This is a good question.

First of all, you should not modify the other files other than ``verify.ml``.

You can address your issue by transforming formulas with Sorted and Partitioned into standard formulas without them (before generating preconditions).

You can find the relevant information at:
https://github.com/gist-pal/ec4219-software-engineering/blob/main/homework/hw1/code/solver.ml#L27-L47

**Comment by tori209** [comment]
Oh, I forgot those definitions. Thank you for your kindness.
