### ISSUE TITLE
[Question/hw1] Z3.Error occurs when "Len" exist in formula.

### ISSUE THREAD

**Issue by tori209** [gist-pal/ec4219-software-engineering#2]
I can't find the reason why this error occurs. I need some help.

I tried to test my code, using "test/linear_search", I encountered Z3.Error exception, saying "domain sort (Array Int Int) and parameter Int do not match". (same error occurs when using "test/bubble_sort".)

I conclude that, maybe `Len` makes some issue when running `check_sat`. Reasons are written below:

---

First, I tried to check satisfiability of precondition. ( 0 ≤ l ∧ u ≤ len(a) ), by filling `run` in verify.ml, using code below.
```
let run
= fun (pre, post, fid, iparams, rparams, cmd) ->
  let is_valid = check_validity pre in
  (is_valid, -1)
```
and I encountered same Error message.

Second, I changed some in "test/linear_search" like: `int a[]` to `int a[16]`, and `len(a)` to 16.
and I found that error disappered.
Below images are screenshots of result, first one is result about original 'linear_search', the other is about modified 'linear_search'.
As it shown, only last one runs with no error.
![original_image](https://github.com/gist-pal/ec4219-software-engineering/assets/52180188/025fad4a-f715-4c4a-83dd-5ef5fa2726c5)
![modified_image](https://github.com/gist-pal/ec4219-software-engineering/assets/52180188/e462db38-c57d-425c-a21a-b51a23c290ed)

At Last, I just rewrite `run` in "verify.ml" and tried to run.
```
let run : pgm -> bool * int
= fun (pre,post,fid,iparams,rparam,cmd) ->
  let av = ("a", Array (ESort Int, ESort Int)) in
  let f = BinRel (Leq, Int 0, Len av) in
  let is_valid = check_validity f in
  (is_valid, -1)
```
and same error occurs.
![image](https://github.com/gist-pal/ec4219-software-engineering/assets/52180188/6c097973-2e42-47ed-958e-4d26bc9eff18)

I can't find why this problem occurs.

**Comment by sunbeomso** [comment]
@tori209

I am really sorry for the late reply and the error in the ``solver.ml``.

In ``solver.ml``, you should make two changes:
1. There was a type error when encoding ``Len`` in Z3, so you should change ``solver.ml`` as follows:
https://github.com/gist-pal/ec4219-software-engineering/blob/26ed6e89b4dd6d2c758ba82e7976c608799405e7/homework/hw1/code/solver.ml#L78-L79

2. As an independent issue (not related to your errors), you should also provide unique names to bound variables for ``Sorted`` and ``Partitioned``:

https://github.com/gist-pal/ec4219-software-engineering/blob/26ed6e89b4dd6d2c758ba82e7976c608799405e7/homework/hw1/code/solver.ml#L27-L29

https://github.com/gist-pal/ec4219-software-engineering/blob/26ed6e89b4dd6d2c758ba82e7976c608799405e7/homework/hw1/code/solver.ml#L36-L38

**Comment by tori209** [comment]
Thanks! Now errors are disappeared.
