### ISSUE TITLE
[Question/hw1] Is there any cases with boolean array?

### ISSUE THREAD

**Issue by tori209** [gist-pal/ec4219-software-engineering#3]
I'm wondering that there's any cases with boolean array.

I found that "DArray Bool" should be handled in given template.
As I understood, The only way to use access one array element is "Read", which is term.
But, Boolean cannot be handled using term.

Should we find method to handle Boolean Array using formula?
Or there's no case with boolean array?

**Comment by sunbeomso** [comment]
That part was unexpectedly introduced during making the template.

For hw1, you can assume that programs containing boolean arrays will not appear for evaluating your submission.

**Comment by tori209** [comment]
Thanks for quick response. It will be very helpful.
