### ISSUE TITLE
[Question/hw3] Question about loop condition in `while`

### ISSUE THREAD

**Issue by tori209** [gist-pal/ec4219-software-engineering#5]
In our lecture notes and test cases, we can find that loop conditions have very simple form, like `i ≤ 10` or `n ＞5`.
But, in practical, complicated inequations like `x+y＜10`, `xy ＜10`, and `x < z` can be loop condition.
(and those forms are acceptable in our language.)

So, before I find a way to implement "filter" considering complicated cases, I have to ask this question:
In our cases, Do every loop condition has simple equations, like `[var] [op] [exp]`, or `[exp] [op] [var]`?

**Comment by sunbeomso** [comment]
Loop conditions can be any expressions as long as the expressions are bool-typed.
For instance, ``x+y > a+b+c && x-y < p*q `` can be a loop condition.

Regarding cases where no information can be refined, you can simply define the filter function as an identity function: ``filter(p)(x) = x``.
